### ISSUE TITLE
There is some perms or wiki?

### ISSUE THREAD

**Issue by RocoWayne** [Driesboy/Parkour#16]

**Comment by Driesboy** [comment]
no perms

**Comment by RocoWayne** [comment]
mmm.. is kind of dangerous for a server i think, can you add some perm? i mean, only for the admin can set the spawnpoint and config the map. 

Thanks for advance!

**Comment by Driesboy** [comment]
ok soon

**Comment by Driesboy** [comment]
add video

**Comment by RocoWayne** [comment]
perms??? Is too dangerous without
