### ISSUE TITLE
Uncaught exception 'ClassNotFoundException' with message 'Class Parkour\CommandSender not found

### ISSUE THREAD

**Issue by Driesboy** [Driesboy/Parkour#17]
Warning: Uncaught exception 'ClassNotFoundException' with message 'Class Parkour\CommandSender not found' in /Users/Ronny/Desktop/Lobby V2/src/spl/BaseClassLoader.php:128
Stack trace:
#0 [internal function]: BaseClassLoader->loadClass('Parkour\\Command...')
#1 /Users/Ronny/Desktop/Lobby V2/plugins/Parkour-3.0/src/Parkour/Main.php(29): spl_autoload_call('Parkour\\Command...')
#2 /Users/Ronny/Desktop/Lobby V2/src/spl/BaseClassLoader.php(112): include('/Users/Ronny/De...')
#3 [internal function]: BaseClassLoader->loadClass('Parkour\\Main')
#4 [internal function]: spl_autoload_call('Parkour\\Main')
#5 phar:///Users/Ronny/Desktop/Lobby V2/plugins/DevTools_v1.10.0.phar/src/FolderPluginLoader/FolderPluginLoader.php(64): class_exists('Parkour\\Main', true)
#6 /Users/Ronny/Desktop/Lobby V2/src/pocketmine/plugin/PluginManager.php(132): FolderPluginLoader\FolderPluginLoader->loadPlugin('/Users/Ronny/De...')
#7 /Users/Ronny/Desktop/Lobby V2/src/pocketmine/plugin/PluginManager.php(276): pocketmine\plugin\PluginManager->loadPlugin( in /Users/Ronny/Desktop/Lobby V2/src/spl/BaseClassLoader.php on line 128

Fatal error: Declaration of Parkour\Main::onCommand() must be compatible with pocketmine\command\CommandExecutor::onCommand(pocketmine\command\CommandSender $sender, pocketmine\command\Command $command, $label, array $args) in /Users/Ronny/Desktop/Lobby V2/plugins/Parkour-3.0/src/Parkour/Main.php on line 29

**Comment by RocoWayne** [comment]
Im having this problem

11.02 06:01:05 [Server] Server thread/INFO Disabling Parkour v2.0.1
11.02 06:01:05 [Server] Server thread/NOTICE RuntimeException: "Argument 1 passed to pocketmine\plugin\PluginManager::registerEvents() must implement interface pocketmine\event\Listener, instance of Parkour\Main given, called in phar:///plugins/Parkour.phar/src/Parkour/Main.php on line 35 and defined" (E_RECOVERABLE_ERROR) in "/jar/pocketmine_php5/src/pocketmine/plugin/PluginManager" at line 698
11.02 06:01:05 [Server] Server thread/INFO By: Driesboy. http://github.com/Driesboy
11.02 06:01:05 [Server] Server thread/INFO Parkour Has Been Enabled.

**Comment by Driesboy** [comment]
ok

**Comment by Driesboy** [comment]
is it on 2.0.1 or 3.0

**Comment by Driesboy** [comment]
i think fixed
