### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by XShockinFireX** [Driesboy/Parkour#20]
Could not pass event 'pocketmine\event\player\PlayerInteractEvent' to 'Parkour v2.0.1': yaml_parse(): end of stream reached without finding document 0 on Parkour\Main

RuntimeException: "yaml_parse(): end of stream reached without finding document 0" (E_WARNING) in "/src/pocketmine/utils/Config" at line 124

**Comment by XShockinFireX** [comment]
Plz fix

**Comment by Driesboy** [comment]
use newest version and remove config
