### ISSUE TITLE
is it fine if i use this plugin in the new gladiatormine  site?

### ISSUE THREAD

**Issue by matthew4444** [Driesboy/Parkour#23]
is it fine if i use this plugin in the new gladiatormine  site?

**Comment by Driesboy** [comment]
yes but i add

**Comment by Driesboy** [comment]
can i get the url

**Comment by matthew4444** [comment]
kk

**Comment by matthew4444** [comment]
u cant its my site,its not xenforo due to someone reported annd closed gladiatormine.net

**Comment by matthew4444** [comment]
ill give credits

**Comment by matthew4444** [comment]
im relly srry

**Comment by Driesboy** [comment]
ok is nothing
